# Generated by Django 2.0.4 on 2018-06-27 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='principal.Fornecedor'),
            preserve_default=False,
        ),
    ]
