# Generated by Django 2.0.4 on 2018-07-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_produto_fornecedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='fornecedor',
        ),
        migrations.AddField(
            model_name='produto',
            name='fornecedor',
            field=models.ManyToManyField(to='principal.Fornecedor'),
        ),
    ]
